"""Initial schema: feedback, customers, companies, classifications

Revision ID: 8e9788757482
Revises: 
Create Date: 2026-06-29 15:59:45.695936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '8e9788757482'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector extension is created in alembic/env.py before the transaction
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('hubspot_company_id', sa.String(length=100), nullable=True),
    sa.Column('zendesk_org_id', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('arr', sa.Integer(), nullable=True),
    sa.Column('decision_maker_count', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=True)
    op.create_index(op.f('ix_companies_hubspot_company_id'), 'companies', ['hubspot_company_id'], unique=False)
    op.create_index('ix_companies_hubspot_id', 'companies', ['hubspot_company_id'], unique=False)
    op.create_index('ix_companies_zendesk_id', 'companies', ['zendesk_org_id'], unique=False)
    op.create_index(op.f('ix_companies_zendesk_org_id'), 'companies', ['zendesk_org_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('hubspot_contact_id', sa.String(length=100), nullable=True),
    sa.Column('zendesk_user_id', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_hubspot_contact_id'), 'customers', ['hubspot_contact_id'], unique=False)
    op.create_index('ix_customers_hubspot_id', 'customers', ['hubspot_contact_id'], unique=False)
    op.create_index('ix_customers_zendesk_id', 'customers', ['zendesk_user_id'], unique=False)
    op.create_index(op.f('ix_customers_zendesk_user_id'), 'customers', ['zendesk_user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source_channel', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('satisfaction_score', sa.String(length=20), nullable=True),
    # Note: embedding column requires pgvector extension
    # sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_company_id', 'feedback', ['company_id'], unique=False)
    op.create_index('ix_feedback_created_at', 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_customer_email'), 'feedback', ['customer_email'], unique=False)
    op.create_index(op.f('ix_feedback_customer_id'), 'feedback', ['customer_id'], unique=False)
    op.create_index(op.f('ix_feedback_external_id'), 'feedback', ['external_id'], unique=False)
    op.create_index('ix_feedback_source', 'feedback', ['source'], unique=False)
    op.create_index('ix_feedback_source_external_id', 'feedback', ['source', 'external_id'], unique=True)
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('product_area', sa.String(length=100), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('classified_at', sa.DateTime(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_category'), 'classifications', ['category'], unique=False)
    op.create_index(op.f('ix_classifications_feedback_id'), 'classifications', ['feedback_id'], unique=True)
    op.create_index(op.f('ix_classifications_sentiment'), 'classifications', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classifications_sentiment'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_feedback_id'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_category'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index('ix_feedback_source_external_id', table_name='feedback')
    op.drop_index('ix_feedback_source', table_name='feedback')
    op.drop_index(op.f('ix_feedback_external_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_customer_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_customer_email'), table_name='feedback')
    op.drop_index('ix_feedback_created_at', table_name='feedback')
    op.drop_index('ix_feedback_company_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_customers_zendesk_user_id'), table_name='customers')
    op.drop_index('ix_customers_zendesk_id', table_name='customers')
    op.drop_index('ix_customers_hubspot_id', table_name='customers')
    op.drop_index(op.f('ix_customers_hubspot_contact_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_companies_zendesk_org_id'), table_name='companies')
    op.drop_index('ix_companies_zendesk_id', table_name='companies')
    op.drop_index('ix_companies_hubspot_id', table_name='companies')
    op.drop_index(op.f('ix_companies_hubspot_company_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###

    # Drop pgvector extension (only if no other tables use it)
    op.execute("DROP EXTENSION IF EXISTS vector")
