"""Classification model - AI-generated labels for feedback."""

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import String, Integer, Float, ForeignKey, DateTime, Index, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.feedback import Feedback


class Classification(Base):
    """
    AI-generated classification for a feedback item.

    Generated by OpenAI/Vertex AI classification pipeline.
    """
    __tablename__ = "classifications"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Link to feedback (one-to-one)
    feedback_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("feedback.id", ondelete="CASCADE"), unique=True, nullable=False
    )

    # Sentiment classification
    sentiment: Mapped[str | None] = mapped_column(String(20))  # positive, negative, neutral, mixed
    sentiment_score: Mapped[float | None] = mapped_column(Float)  # -1.0 to 1.0

    # Category classification
    category: Mapped[str | None] = mapped_column(String(100))  # bug, feature_request, question, complaint, praise
    category_confidence: Mapped[float | None] = mapped_column(Float)  # 0.0 to 1.0

    # Product area (if detected)
    product_area: Mapped[str | None] = mapped_column(String(100))  # billing, auth, api, ui, etc.

    # Key topics/themes extracted
    topics: Mapped[list[str] | None] = mapped_column(JSON)  # ["performance", "mobile", "integration"]

    # AI-generated summary (1-2 sentences)
    summary: Mapped[str | None] = mapped_column(String(500))

    # Classification metadata
    model_used: Mapped[str | None] = mapped_column(String(100))  # gpt-4o-mini, gemini-2.0-flash-exp
    model_version: Mapped[str | None] = mapped_column(String(50))
    classified_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=datetime.utcnow)

    # Raw AI response (for debugging/reprocessing)
    raw_response: Mapped[dict | None] = mapped_column(JSON)

    # Relationships
    feedback: Mapped["Feedback"] = relationship("Feedback", back_populates="classification")

    __table_args__ = (
        Index("ix_classifications_feedback_id", "feedback_id"),
        Index("ix_classifications_sentiment", "sentiment"),
        Index("ix_classifications_category", "category"),
    )

    def __repr__(self) -> str:
        return f"<Classification(id={self.id}, feedback_id={self.feedback_id}, sentiment='{self.sentiment}', category='{self.category}')>"
